[general]
import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
decorations			= "None"
padding					= { x = 2, y = 2 }
dynamic_padding	= true
opacity					= 0.8
startup_mode		= "Fullscreen"

[cursor]
style						= { shape = "Block", blinking = "Always" }
blink_interval	= 750
blink_timeout		= 5
