[window]
decorations			= "None"
dynamic_padding	= true
opacity					= 0.8
startup_mode		= "Fullscreen"

[cursor]
style						= { shape = "Block", blinking = "Always" }
blink_interval	= 750
blink_timeout		= 5
